name: flutter_open_street_map
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 18.4.30

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0

  syncfusion_flutter_datagrid: ^25.2.7
  syncfusion_flutter_calendar: ^25.2.7+1
  syncfusion_flutter_datepicker: ^25.2.7
  syncfusion_flutter_charts: ^25.2.7
  syncfusion_flutter_gauges: ^25.2.7
  syncfusion_flutter_sliders: ^25.2.7
  syncfusion_flutter_pdf: ^25.2.7
  syncfusion_flutter_barcodes: ^25.2.7
  syncfusion_officechart: ^25.2.7
  syncfusion_flutter_maps: ^25.2.7
  syncfusion_flutter_signaturepad: ^25.2.7
  syncfusion_flutter_pdfviewer: ^25.2.7
  syncfusion_flutter_treemap: ^25.2.7


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - images/xlsio/
    - lib/sample_details.json
    - assets/world_map.json
    - assets/africa.json
    - assets/europe.json
    - assets/india.json
    - assets/usa.json
    - assets/south_america.json
    - assets/australia.json
    - assets/maps_brazil_boundary.json
    - assets/maps_uk_boundary.json
    - assets/maps_france_boundary.json
    - assets/river.json
    - assets/london_to_british.json
    - assets/london_to_chessington.json
    - assets/london_to_hampton_court_palace.json
    - assets/london_to_twickenham_stadium.json
    - assets/london_to_windsor_castle.json
    - assets/product_data.json
    - assets/chart_data.json
#  fonts:
#    - family: HeeboBold
#      fonts:
#        - assets: assets/fonts/Heebo-Bold.ttf
#    - family: HeeboMedium
#      fonts:
#        - assets: assets/fonts/Heebo-Medium.ttf
#    - family: Roboto-Bold
#      fonts:
#        - assets: assets/fonts/Roboto-Bold.ttf
#    - family: Roboto-Medium
#      fonts:
#        - assets: assets/fonts/Roboto-Medium.ttf
#    - family: Roboto-Regular
#      fonts:
#        - assets: assets/fonts/Roboto-Regular.ttf
